export const TEXAS_CITIES = [
  'Abilene',
  'Amarillo',
  'Arlington',
  'Austin',
  'Baytown',
  'Beaumont',
  'Bedford',
  'Brownsville',
  'Bryan',
  'Burleson',
  'Carrollton',
  'Cedar Park',
  'Cibolo',
  'Cleburne',
  'College Station',
  'Conroe',
  'Coppell',
  'Copperas Cove',
  'Corpus Christi',
  'Dallas',
  'Del Rio',
  'Denton',
  'DeSoto',
  'Edinburg',
  'El Paso',
  'Euless',
  'Fort Worth',
  'Friendswood',
  'Frisco',
  'Galveston',
  'Garland',
  'Georgetown',
  'Grand Prairie',
  'Grapevine',
  'Haltom City',
  'Harlingen',
  'Houston',
  'Huntsville',
  'Irving',
  'Keller',
  'Kerrville',
  'Killeen',
  'Kyle',
  'Lancaster',
  'Laredo',
  'League City',
  'Leander',
  'Lewisville',
  'Little Elm',
  'Longview',
  'Lubbock',
  'Mansfield',
  'McAllen',
  'McKinney',
  'Mesquite',
  'Midland',
  'Mission',
  'Missouri City',
  'Nacogdoches',
  'New Braunfels',
  'Odessa',
  'Paris',
  'Pasadena',
  'Pearland',
  'Pflugerville',
  'Pharr',
  'Plano',
  'Port Arthur',
  'Prosper',
  'Richardson',
  'Rockwall',
  'Round Rock',
  'Rowlett',
  'San Angelo',
  'San Antonio',
  'San Benito',
  'San Juan',
  'San Marcos',
  'Schertz',
  'Seguin',
  'Sherman',
  'Socorro',
  'Sugar Land',
  'Temple',
  'Texarkana',
  'Texas City',
  'The Woodlands',
  'Tyler',
  'Victoria',
  'Waco',
  'Waxahachie',
  'Weatherford',
  'Weslaco',
  'Wylie',
];
