import { CaregiverProfileDetails, Caregiver } from '@/features/leaderboard';

const MOCK_CAREGIVERS: Record<string, Caregiver> = {
  'john-doe': {
    rank: 1,
    name: 'John Doe',
    avatar: '/images/avatar.webp',
    rating: 4.9,
    reviewsCount: 32,
    servicesCount: 75,
    completedServicesCount: 1250,
    verified: true,
    message: 'Experienced companion caregiver specializing in senior support, recreational activities, and personal care assistance. Committed to enabling independent living with warmth and patience.',
  },
  'nandi-bolard': {
    rank: 2,
    name: 'Nandi Bolard',
    avatar: '/images/avatar.webp',
    rating: 5.0,
    reviewsCount: 48,
    servicesCount: 98,
    completedServicesCount: 1450,
    verified: true,
    message: 'Passionate and certified companion specialist with over 7 years in social assistance, hobby facilitation, and transportation help for seniors.',
  },
  'mark-taylor': {
    rank: 3,
    name: 'Mark Taylor',
    avatar: '/images/avatar.webp',
    rating: 4.8,
    reviewsCount: 22,
    servicesCount: 50,
    completedServicesCount: 980,
    verified: true,
    message: 'Caring, friendly assistant providing conversational companionship, household chore support, and cognitive exercise games for elderly clients.',
  },
  'james-brown': {
    rank: 4,
    name: 'James Brown',
    avatar: '/images/giver.webp',
    rating: 4.7,
    reviewsCount: 42,
    servicesCount: 65,
    completedServicesCount: 1090,
    verified: true,
    message: 'Reliable and punctual professional with extensive history in companion service care, meal prep, and appointment coordination.',
  },
  'sara-wilson': {
    rank: 5,
    name: 'Sara Wilson',
    avatar: '/images/avatar.webp',
    rating: 4.7,
    reviewsCount: 25,
    servicesCount: 38,
    completedServicesCount: 890,
    verified: true,
    message: 'Dedicated support caregiver focused on companion therapy, mobility support, and creating safe, joyful social environments.',
  },
  'maria-garcia': {
    rank: 6,
    name: 'Maria Garcia',
    avatar: '/images/giver.webp',
    rating: 4.5,
    reviewsCount: 19,
    servicesCount: 28,
    completedServicesCount: 850,
    verified: false,
    message: 'Attentive caregiver offering compassionate companion visits, memory reinforcement games, and light housework help.',
  },
  'samuel-lee': {
    rank: 7,
    name: 'Samuel Lee',
    avatar: '/images/seeker.webp',
    rating: 4.8,
    reviewsCount: 52,
    servicesCount: 115,
    completedServicesCount: 1200,
    verified: true,
    message: 'Experienced and high-rated care specialist focusing on senior companion care and interactive mental wellness support.',
  },
  'anna-smith': {
    rank: 8,
    name: 'Anna Smith',
    avatar: '/images/giver.webp',
    rating: 4.9,
    reviewsCount: 30,
    servicesCount: 52,
    completedServicesCount: 950,
    verified: true,
    message: 'Focused companion assistant, trained in physical guidance assistance, cognitive support, and dietary needs helper.',
  },
  'michael-johnson': {
    rank: 9,
    name: 'Michael Johnson',
    avatar: '/images/avatar.webp',
    rating: 4.6,
    reviewsCount: 28,
    servicesCount: 45,
    completedServicesCount: 1150,
    verified: true,
    message: 'Certified assistant with a focus on senior social integration and mobility assistance in home care settings.',
  },
  'laura-wilson': {
    rank: 10,
    name: 'Laura Wilson',
    avatar: '/images/seeker.webp',
    rating: 4.4,
    reviewsCount: 15,
    servicesCount: 22,
    completedServicesCount: 780,
    verified: false,
    message: 'Friendly assistant providing supportive companion care, shopping trips assistance, and light household organization help.',
  },
  'elena-torres': {
    rank: 1,
    name: 'Elena Torres',
    avatar: '/images/avatar.webp',
    rating: 4.95,
    reviewsCount: 56,
    servicesCount: 120,
    completedServicesCount: 1780,
    verified: true,
    message: 'Certified Nursing Assistant (CNA) offering top-tier personal hygiene, grooming, and mobility support. Patient and professional approach to home care.',
  },
  'ava-hart': {
    rank: 2,
    name: 'Ava Hart',
    avatar: '/images/seeker.webp',
    rating: 4.9,
    reviewsCount: 40,
    servicesCount: 88,
    completedServicesCount: 1350,
    verified: true,
    message: 'Experienced care provider specializing in personal safety, transfers, and medical compliance routines in a home environment.',
  },
  'lucas-grant': {
    rank: 3,
    name: 'Lucas Grant',
    avatar: '/images/avatar.webp',
    rating: 4.8,
    reviewsCount: 30,
    servicesCount: 64,
    completedServicesCount: 1050,
    verified: true,
    message: 'Caring personal caregiver focused on dignity-preserving hygiene care, dressing help, and light physical therapy support.',
  },
  'jamal-edwards': {
    rank: 4,
    name: 'Jamal Edwards',
    avatar: '/images/giver.webp',
    rating: 4.75,
    reviewsCount: 35,
    servicesCount: 72,
    completedServicesCount: 1180,
    verified: true,
    message: 'Attentive assistant trained in transfer protocols, bathing assistance, and post-operative home rehabilitation care.',
  },
  'olivia-james': {
    rank: 5,
    name: 'Olivia James',
    avatar: '/images/seeker.webp',
    rating: 4.7,
    reviewsCount: 28,
    servicesCount: 50,
    completedServicesCount: 920,
    verified: true,
    message: 'Professional homecare practitioner providing consistent bathing support, meal prep, and grooming help.',
  },
};

interface PageProps {
  params: Promise<{ id: string }>;
}

export default async function Page({ params }: PageProps) {
  const { id } = await params;
  const caregiver = MOCK_CAREGIVERS[id] || MOCK_CAREGIVERS['john-doe'];

  return <CaregiverProfileDetails caregiver={{ ...caregiver, id }} />;
}
